-- =====================================================
-- RESTAURANTOS - ÓRDENES, DETALLE Y PAGOS
-- =====================================================

-- =====================================================
-- ORDERS
-- =====================================================

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),

  order_number bigint
    generated by default as identity
    unique,

  table_label text,
  customer_name text,

  status text not null default 'open'
    check (
      status in (
        'open',
        'preparing',
        'ready',
        'served',
        'closed',
        'cancelled'
      )
    ),

  payment_status text not null default 'unpaid'
    check (
      payment_status in (
        'unpaid',
        'partial',
        'paid'
      )
    ),

  notes text,

  subtotal numeric(12, 2) not null default 0
    check (subtotal >= 0),

  discount numeric(12, 2) not null default 0
    check (discount >= 0),

  total numeric(12, 2) not null default 0
    check (total >= 0),

  created_by uuid
    default auth.uid()
    references public.profiles(id)
    on delete set null,

  assigned_to uuid
    references public.profiles(id)
    on delete set null,

  paid_at timestamptz,
  closed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =====================================================
-- ORDER ITEMS
-- =====================================================

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),

  order_id uuid not null
    references public.orders(id)
    on delete cascade,

  product_id uuid
    references public.products(id)
    on delete set null,

  -- Copia histórica del producto al momento de venderlo.
  product_name text not null,

  unit_price numeric(12, 2) not null
    check (unit_price >= 0),

  quantity integer not null default 1
    check (quantity > 0),

  notes text,

  line_total numeric(12, 2)
    generated always as (unit_price * quantity) stored,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =====================================================
-- PAYMENTS
-- =====================================================

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),

  order_id uuid not null
    references public.orders(id)
    on delete cascade,

  amount numeric(12, 2) not null
    check (amount > 0),

  method text not null
    check (
      method in (
        'cash',
        'card',
        'transfer',
        'other'
      )
    ),

  status text not null default 'completed'
    check (
      status in (
        'completed',
        'voided',
        'refunded'
      )
    ),

  reference text,
  notes text,

  received_by uuid
    default auth.uid()
    references public.profiles(id)
    on delete set null,

  paid_at timestamptz not null default now(),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =====================================================
-- ÍNDICES
-- =====================================================

create index if not exists orders_status_idx
on public.orders(status);

create index if not exists orders_payment_status_idx
on public.orders(payment_status);

create index if not exists orders_created_at_idx
on public.orders(created_at desc);

create index if not exists orders_created_by_idx
on public.orders(created_by);

create index if not exists orders_assigned_to_idx
on public.orders(assigned_to);

create index if not exists order_items_order_id_idx
on public.order_items(order_id);

create index if not exists order_items_product_id_idx
on public.order_items(product_id);

create index if not exists payments_order_id_idx
on public.payments(order_id);

create index if not exists payments_method_idx
on public.payments(method);

create index if not exists payments_paid_at_idx
on public.payments(paid_at desc);


-- =====================================================
-- UPDATED_AT
-- Reutiliza public.set_updated_at() creada previamente.
-- =====================================================

drop trigger if exists orders_set_updated_at
on public.orders;

create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();


drop trigger if exists order_items_set_updated_at
on public.order_items;

create trigger order_items_set_updated_at
before update on public.order_items
for each row
execute function public.set_updated_at();


drop trigger if exists payments_set_updated_at
on public.payments;

create trigger payments_set_updated_at
before update on public.payments
for each row
execute function public.set_updated_at();


-- =====================================================
-- CALCULAR TOTAL DE LA ORDEN
-- total = subtotal - descuento
-- =====================================================

create or replace function public.compute_order_total()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.total := greatest(
    coalesce(new.subtotal, 0) - coalesce(new.discount, 0),
    0
  );

  return new;
end;
$$;


drop trigger if exists orders_compute_total
on public.orders;

create trigger orders_compute_total
before insert or update of subtotal, discount
on public.orders
for each row
execute function public.compute_order_total();


-- =====================================================
-- ACTUALIZAR ESTADO DE PAGO
-- =====================================================

create or replace function public.refresh_order_payment_status(
  p_order_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_total numeric(12, 2);
  v_paid numeric(12, 2);
  v_payment_status text;
begin
  select total
  into v_total
  from public.orders
  where id = p_order_id;

  if not found then
    return;
  end if;

  select coalesce(sum(amount), 0)
  into v_paid
  from public.payments
  where order_id = p_order_id
    and status = 'completed';

  v_payment_status :=
    case
      when v_total > 0 and v_paid >= v_total then 'paid'
      when v_paid > 0 then 'partial'
      else 'unpaid'
    end;

  update public.orders
  set
    payment_status = v_payment_status,
    paid_at = case
      when v_payment_status = 'paid'
        then coalesce(paid_at, now())
      else null
    end
  where id = p_order_id;
end;
$$;


-- =====================================================
-- RECALCULAR SUBTOTAL DESDE ORDER_ITEMS
-- =====================================================

create or replace function public.refresh_order_totals(
  p_order_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_subtotal numeric(12, 2);
begin
  select coalesce(sum(line_total), 0)
  into v_subtotal
  from public.order_items
  where order_id = p_order_id;

  update public.orders
  set subtotal = v_subtotal
  where id = p_order_id;
end;
$$;


create or replace function public.handle_order_items_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_order_totals(old.order_id);
    return old;
  end if;

  if tg_op = 'UPDATE'
    and old.order_id is distinct from new.order_id
  then
    perform public.refresh_order_totals(old.order_id);
  end if;

  perform public.refresh_order_totals(new.order_id);

  return new;
end;
$$;


drop trigger if exists order_items_refresh_order
on public.order_items;

create trigger order_items_refresh_order
after insert or update or delete
on public.order_items
for each row
execute function public.handle_order_items_change();


-- =====================================================
-- RECALCULAR ESTADO CUANDO CAMBIA EL TOTAL
-- =====================================================

create or replace function public.handle_order_total_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.refresh_order_payment_status(new.id);
  return new;
end;
$$;


drop trigger if exists orders_refresh_payment_status
on public.orders;

create trigger orders_refresh_payment_status
after update of total
on public.orders
for each row
when (old.total is distinct from new.total)
execute function public.handle_order_total_change();


-- =====================================================
-- RECALCULAR ESTADO CUANDO CAMBIAN LOS PAGOS
-- =====================================================

create or replace function public.handle_payments_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_order_payment_status(old.order_id);
    return old;
  end if;

  if tg_op = 'UPDATE'
    and old.order_id is distinct from new.order_id
  then
    perform public.refresh_order_payment_status(old.order_id);
  end if;

  perform public.refresh_order_payment_status(new.order_id);

  return new;
end;
$$;


drop trigger if exists payments_refresh_order
on public.payments;

create trigger payments_refresh_order
after insert or update or delete
on public.payments
for each row
execute function public.handle_payments_change();


-- =====================================================
-- CLOSED_AT AUTOMÁTICO
-- =====================================================

create or replace function public.set_order_closed_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = 'closed'
    and old.status is distinct from 'closed'
  then
    new.closed_at := now();
  elsif new.status <> 'closed' then
    new.closed_at := null;
  end if;

  return new;
end;
$$;


drop trigger if exists orders_set_closed_at
on public.orders;

create trigger orders_set_closed_at
before update of status
on public.orders
for each row
execute function public.set_order_closed_at();