
-- =====================================================
-- RESTAURANTOS - CIERRES DE CAJA
-- Sin apertura de caja ni sesiones.
-- =====================================================

create table if not exists public.cash_closures (
  id uuid primary key default gen_random_uuid(),

  closure_number bigint
    generated by default as identity
    unique,

  closed_at timestamptz not null default now(),

  closed_by uuid not null
    default auth.uid()
    references public.profiles(id)
    on delete restrict,

  orders_count integer not null default 0
    check (orders_count >= 0),

  payments_count integer not null default 0
    check (payments_count >= 0),

  cash_total numeric(12, 2) not null default 0
    check (cash_total >= 0),

  card_total numeric(12, 2) not null default 0
    check (card_total >= 0),

  transfer_total numeric(12, 2) not null default 0
    check (transfer_total >= 0),

  other_total numeric(12, 2) not null default 0
    check (other_total >= 0),

  total numeric(12, 2)
    generated always as (
      cash_total
      + card_total
      + transfer_total
      + other_total
    ) stored,

  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =====================================================
-- RELACIONAR PAGOS Y ÓRDENES CON EL CIERRE
-- =====================================================

alter table public.payments
add column if not exists cash_closure_id uuid
  references public.cash_closures(id)
  on delete restrict;

alter table public.orders
add column if not exists cash_closure_id uuid
  references public.cash_closures(id)
  on delete restrict;


-- =====================================================
-- ÍNDICES
-- =====================================================

create index if not exists cash_closures_closed_at_idx
on public.cash_closures(closed_at desc);

create index if not exists cash_closures_closed_by_idx
on public.cash_closures(closed_by);

create index if not exists payments_cash_closure_id_idx
on public.payments(cash_closure_id);

create index if not exists orders_cash_closure_id_idx
on public.orders(cash_closure_id);


-- =====================================================
-- UPDATED_AT AUTOMÁTICO
-- Reutiliza public.set_updated_at()
-- =====================================================

drop trigger if exists cash_closures_set_updated_at
on public.cash_closures;

create trigger cash_closures_set_updated_at
before update on public.cash_closures
for each row
execute function public.set_updated_at();